### ISSUE TITLE
Device Unsupported issue with GTX 1060 

### ISSUE THREAD

**Issue by sideshow6** [jakibaki/In-Home-Switching#41]
Every time I run the app on windows and click connect, I always get this. (see below) Installed all latest drivers. Have GTX 1060 6gb on custom built comp which has featured levels for 12.0, 11.1 and 11.0, checked Nvidia Control Panel. Searched online for days and tired several solutions to no avail before posting here

************** Exception Text **************
SharpDX.SharpDXException: HRESULT: [0x887A0004], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_UNSUPPORTED/Unsupported], Message: The specified device interface or feature level is not supported on this system.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateDevice(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
   at InHomeSwitching.DesktopDuplicator..ctor(Int32 whichGraphicsCardAdapter, Int32 whichOutputDevice)
   at InHomeSwitching.Window.Streamer.InitConnection()
   at InHomeSwitching.Window.Streamer.Start(String ip, Int32 quality)
   at InHomeSwitching.Window.Window.Toggle_button_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

also checked Dxdiag and keep getting

+++ WER9 +++:
Fault bucket 1820766021738459595, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: In-Home-Switching.exe

system settings from dx diag
  Operating System: Windows 10 Pro 64-bit (10.0, Build 17134) (17134.rs4_release.180410-1804)
                 Language: English (Regional Setting: English)
      System Manufacturer: To Be Filled By O.E.M.
             System Model: To Be Filled By O.E.M.
                     BIOS: BIOS Date: 11/07/17 21:38:35 Ver: 05.0000C (type: BIOS)
                Processor: AMD Ryzen 7 1700X Eight-Core Processor          (16 CPUs), ~3.4GHz
                   Memory: 24576MB RAM
      Available OS Memory: 24508MB RAM
                Page File: 5910MB used, 22181MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.17134.0001 64bit Unicode

 Card name: NVIDIA GeForce GTX 1060 6GB
        Manufacturer: NVIDIA
           Chip type: GeForce GTX 1060 6GB
            DAC type: Integrated RAMDAC
         Device Type: Full Device (POST)
          Device Key: Enum\PCI\VEN_10DE&DEV_1C03&SUBSYS_85A41043&REV_A1
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 18306 MB
    Dedicated Memory: 6052 MB
       Shared Memory: 12254 MB
        Current Mode: 1920 x 1080 (32 bit) (60Hz)
         HDR Support: Not Supported
    Display Topology: Internal
 Display Color Space: DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
     Color Primaries: Red(0.645031,0.336437), Green(0.318859,0.615734), Blue(0.146008,0.055188), White Point(0.313977,0.329602)
   Display Luminance: Min Luminance = 0.500000, Max Luminance = 270.000000, MaxFullFrameLuminance = 270.000000
        Monitor Name: HP 23tm Touch Monitor
       Monitor Model: HP 23tm
          Monitor Id: HWP3110
         Native Mode: 1920 x 1080(p) (60.000Hz)
         Output Type: HDMI
Monitor Capabilities: HDR Not Supported
Display Pixel Format: DISPLAYCONFIG_PIXELFORMAT_32BPP
      Advanced Color: Not Supported
         Driver Name: C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5db32447b43ce666\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5db32447b43ce666\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5db32447b43ce666\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5db32447b43ce666\nvldumdx.dll
 Driver File Version: 25.21.0014.1771 (English)
      Driver Version: 25.21.14.1771
         DDI Version: 12
      Feature Levels: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 2.4
 Graphics Preemption: Pixel
  Compute Preemption: Dispatch
            Miracast: Not Supported by Graphics driver
 Hybrid Graphics GPU: Not Supported
      Power P-states: Not Supported
      Virtualization: Paravirtualization 
          Block List: No Blocks
  Catalog Attributes: Universal:False Declarative:False 
   Driver Attributes: Final Retail
    Driver Date/Size: 1/10/2019 7:00:00 PM, 957616 bytes

**Comment by BetaLeaf** [comment]
I have an Alienware 17 R4 with a GTX 1060 6GB and works fine.

[DxDiag.txt](https://github.com/jakibaki/In-Home-Switching/files/3681021/DxDiag.txt)
