### ISSUE TITLE
Won't connect while using 90dns

### ISSUE THREAD

**Issue by DakotaPixel** [jakibaki/In-Home-Switching#44]
I don't wanna directly connect my switch to internet and get banned, but when using it 90dns the windows client won't connect to the switch.

**Comment by JiNama** [comment]
Working fine for me. I'm using PRIMARY: 163.172.141.219 and SECONDARY: 045.248.048.062 running SXOS V2.5.2 and In-Home-Switching V0.2. Could be a Windows issue.

**Comment by JiNama** [comment]
Did you also install the [Scp drivers](https://github.com/mogzol/ScpDriverInterface/releases/download/1.1/ScpDriverInterface_v1.1.zip)?

**Comment by DakotaPixel** [comment]
I have the scp drivers installed, I even have reinstalled them for it to do the same thing.

**Comment by JiNama** [comment]
Hmm, very weird. The memory (RAM) usage is the same with mine (very high), but I'm not experiencing any crashes of the sort. I'm certain this has nothing to do with 90DNS though, it has something to due with the Windows application. Have you tried running as administrator? Or maybe try setting the priority of the In-Home-Switching application to **high**?

**Comment by DakotaPixel** [comment]
i have tried running as admin, and still have it crash. How would i go about setting priority settings in windows.

**Comment by JiNama** [comment]
In task manager, go to `Details` and right click the process and go to **priority**, then **high**.

![untitled-1](https://user-images.githubusercontent.com/37218166/52379959-64459280-2a42-11e9-86ee-5f2b787835d7.jpg)

**Comment by DakotaPixel** [comment]
this time it gave me an actual error
![oof](https://user-images.githubusercontent.com/43079681/52445418-10e24b80-2af9-11e9-9bac-9b35002841d5.PNG)

full text:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
SharpDX.SharpDXException: HRESULT: [0x8007000E], Module: [General], ApiCode: [E_OUTOFMEMORY/Out of memory], Message: Not enough storage is available to complete this operation.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateDevice(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
   at InHomeSwitching.DesktopDuplicator..ctor(Int32 whichGraphicsCardAdapter, Int32 whichOutputDevice)
   at InHomeSwitching.Window.Streamer.initConnection()
   at InHomeSwitching.Window.Streamer.Start(String ip, Int32 quality)
   at InHomeSwitching.Window.Window.toggle_button_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
DesktopDuplication.Demo
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/downlods/In-Home-Switching.v0.1%20(1)/In-Home-Switching.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3314.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ScpDriverInterface
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/downlods/In-Home-Switching.v0.1%20(1)/ScpDriverInterface.DLL
----------------------------------------
DesktopDuplication
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/downlods/In-Home-Switching.v0.1%20(1)/DesktopDuplication.DLL
----------------------------------------
SharpDX.Direct3D11
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///D:/downlods/In-Home-Switching.v0.1%20(1)/SharpDX.Direct3D11.DLL
----------------------------------------
SharpDX.DXGI
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///D:/downlods/In-Home-Switching.v0.1%20(1)/SharpDX.DXGI.DLL
----------------------------------------
SharpDX
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///D:/downlods/In-Home-Switching.v0.1%20(1)/SharpDX.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by JiNama** [comment]
You're right, that shouldn't be an issue. My only other thought is to try and reinstall the Microsoft Visual C++ 20XX Redistributables, but I'm not sure which year specifically you'd even need. Also, did you download the audio drivers [linked in the README?](https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases) Other than that, I genuinely don't know what the issue could be. Maybe one of the core contributors could help you out.

**Comment by DakotaPixel** [comment]
I will update if I can get it working, but for now I guess I am out of luck on my computer

**Comment by LetsBladeHD** [comment]
Same Issue here. Same Specs and Same Steps done. 

Any Solutions rn?

**Comment by DakotaPixel** [comment]
I really wanted to get this working so I decided to duel boot my windows 10 with windows 8 just so I can use this. It worked so I just made a shortcut to my steam on the windows 8 desktop and installed the drivers for the PC. This is the only solution I have found to this problem, but IDK.

**Comment by nahob** [comment]
@DakotaPixel i have the same problem. did you find answers?
