### ISSUE TITLE
In-Home-Switching.exe crashing on connect

### ISSUE THREAD

**Issue by Ailron09** [jakibaki/In-Home-Switching#9]
After typing in the switch IP(confirmed I can ping it from the computer I'm opening the app on) and clicking connect, the GUI freezes and then goes to (Not Responding) along the top.  After a few moments it just crashes.  I installed the SCP driver and rebooted before trying this.

**Comment by Ailron09** [comment]
Application Event Viewer log:

Application: In-Home-Switching.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.ExternalException
   at System.Drawing.Graphics.MeasureString(System.String, System.Drawing.Font, System.Drawing.SizeF, System.Drawing.StringFormat)
   at System.Drawing.Graphics.MeasureString(System.String, System.Drawing.Font, Int32)
   at System.Windows.Forms.ThreadExceptionDialog..ctor(System.Exception)
   at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)
   at System.Windows.Forms.Control.WndProcException(System.Exception)
   at System.Windows.Forms.Control+ControlNativeWindow.OnThreadException(System.Exception)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at InHomeSwitching.Window.Program.Main()


Immediately after, another error in Event viewer(might contain useful info?):

Faulting application name: In-Home-Switching.exe, version: 1.0.0.0, time stamp: 0x5c12ca8e
Faulting module name: KERNELBASE.dll, version: 10.0.17134.441, time stamp: 0x3da51fd0
Exception code: 0xe0434352
Fault offset: 0x00111812
Faulting process id: 0x1480
Faulting application start time: 0x01d493bea090b946
Faulting application path: C:\Users\Knaue\Desktop\In-Home-Switching v0.1 (1)\Windows\In-Home-Switching.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 314e74e9-0da3-498c-b55e-ef5fb7dae573
Faulting package full name: 
Faulting package-relative application ID:

**Comment by xboxexpert** [comment]
MS.NET version perhaps?

**Comment by xboxexpert** [comment]
To me it looks like .NETFramework,Version=v4.6.1 is needed specifically.    I'm unsure of why it would not work with 4.7.2 but the error is reporting something about v4.0.30319.    My professional IT mind would tell you to remove older outdated framework versions however I am not responsible for any issues you may have after doing so with other software's that may be reliant on older versions.

**Comment by Ailron09** [comment]
Testing now(I've got solid backup solutions, not worried about it), will let you know how it goes!

**Comment by Ailron09** [comment]
Other than the integrated installs of .Net(mine is at 4.7.2) there aren't any others installed.  I've updated my graphics drivers in an attempt to fix as well but that failed.  At this point I'm going to do some digging and tinkering, but was able to get the app to work on my desktop computer.  This is my gaming laptop that I'm working from and is quite a bit stronger so would of course prefer to use it.  Bottom line, obviously not your app, something with my computer settings.

**Comment by D-VAmpire** [comment]
> Bottom line, obviously not your app, something with my computer settings.

So I may close this issue then?

**Comment by UsableName** [comment]
The solution to this is to switch to integrated graphics if you're using a laptop that has both an integrated one and another one (Like most gaming laptops). You can do this by using the NVIDIA control panel (Not too keen about AMD).
